# Generated by Django 3.2 on 2022-04-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupon',
            new_name='DiscountCoupon',
        ),
    ]
