# Generated by Django 3.2 on 2022-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_rename_coupon_discountcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='discount',
            field=models.FloatField(default=100, max_length=100),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='name',
            field=models.CharField(default='Msd', max_length=100),
        ),
    ]
