# Generated by Django 3.2 on 2022-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_auto_20220422_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Msd', max_length=100)),
                ('discount', models.FloatField(default=100, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DiscountCoupon',
        ),
    ]
